### PR TITLE
Handling Missing Verses, and Chapters

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/usfm-js/13)

### CODE REVIEW

**Comment by klappy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/js/usfmToJson.js, line 61 at r1](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-KvDzTuH0yWYsigwx5m6:-KvDzTuH0yWYsigwx5m7:b-ti70ys) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/ac9ca603c88de7fc144ad8746b4a90b24c36567f/src/js/usfmToJson.js#L61)):*
> ```JavaScript
>  * @return {Array} - array of objects that describe open/close and content
> */
> exports.parseLine = function (line) {
> ```

The space here causes it to fail linting.
Can you fix all of the spaces between function and the params? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13)*

**Comment by klappy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/js/usfmToJson.js, line 67 at r1](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-KvE--rHPvmBTBkvuVh6:-KvE--rHPvmBTBkvuVh7:b-kh1p3n) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/ac9ca603c88de7fc144ad8746b4a90b24c36567f/src/js/usfmToJson.js#L67)):*
> ```JavaScript
>     return [{
>       type: 'id',
>       content: idMatch[1],
> ```

removing the trailing comma breaks our linting as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13)*

**Comment by klappy** [comment]
Can you create a test to show what was failing before?
I'm unclear how this behaves any differently than it did before.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-:-KvE-eB5XTN8KRzEygx-:b-g0k66h)*

**Comment by klappy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/js/usfmToJson.js, line 139 at r1](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-KvE1CGy_PJkkw2dQpi8:-KvE1CGy_PJkkw2dQpi9:b-slr2eg) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/ac9ca603c88de7fc144ad8746b4a90b24c36567f/src/js/usfmToJson.js#L139)):*
> ```JavaScript
>         currentVerse = marker.number;
>         if (chapters[currentChapter] && marker.content && !onSameChapter) {
>           //if the current chapter exists, not on same chapter, and there is content to store
> ```

I'm not sure what this adds. Can you add a test for this?
That way we can see an example of what broke before adding this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13)*

**Comment by klappy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/usfmToJson.js, line 64 at r1](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-KvE1M60P-AfbYSSXIBy:-KvE1M60P-AfbYSSXIBz:bqkmrea) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/ac9ca603c88de7fc144ad8746b4a90b24c36567f/src/js/usfmToJson.js#L64)):*
> ```JavaScript
>   let array = []; // = [ { marker: undefined, text: undefined } ]
>   if (/\\id\s/.test(line)) {
>     let idMatch = line.match(/\\id\s(.*)/) || [""]
> ```

I'm not sure what this adds. Can you add a test for this?
That way we can see an example of what broke before adding this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13)*

**Comment by RoyalSix** [comment]
Review status: 0 of 24 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/js/usfmToJson.js, line 61 at r1](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-KvDzTuH0yWYsigwx5m6:-KvEYD_K35X64FBobI2F:bt2vr1b) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/ac9ca603c88de7fc144ad8746b4a90b24c36567f/src/js/usfmToJson.js#L61)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

The space here causes it to fail linting.
Can you fix all of the spaces between function and the params? 
</blockquote></details>

Fixed.

---

*[src/js/usfmToJson.js, line 64 at r1](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-KvE1M60P-AfbYSSXIBy:-KvEh-YDQStjPF1dN73M:b-896fix) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/ac9ca603c88de7fc144ad8746b4a90b24c36567f/src/js/usfmToJson.js#L64)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'm not sure what this adds. Can you add a test for this?
That way we can see an example of what broke before adding this?
</blockquote></details>

Done.

---

*[src/js/usfmToJson.js, line 67 at r1](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-KvE--rHPvmBTBkvuVh6:-KvEjMtuRZv8o7lC4bvd:bt2vr1b) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/ac9ca603c88de7fc144ad8746b4a90b24c36567f/src/js/usfmToJson.js#L67)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

removing the trailing comma breaks our linting as well.
</blockquote></details>

Fixed.

---

*[src/js/usfmToJson.js, line 139 at r1](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-KvE1CGy_PJkkw2dQpi8:-KvEjKkd8QxWhvrACDuK:b-896fix) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/ac9ca603c88de7fc144ad8746b4a90b24c36567f/src/js/usfmToJson.js#L139)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'm not sure what this adds. Can you add a test for this?
That way we can see an example of what broke before adding this?

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13)*

**Comment by klappy** [comment]
*[.eslintrc.js, line 5 at r2](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-KvMiuX__6vWkA3GiPS2:-KvMiuX__6vWkA3GiPS3:b-hgt3sn) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/a821b4c64985ad657badff64ae0bf7b18ac228a3/.eslintrc.js#L5)):*
> ```JavaScript
>     "rules": {
>         "max-len": ["error", { "ignoreStrings": true, ignoreComments:true }],
>         "no-unused-expressions":0
> ```

What are these updated rules for? 
We should probably sync up on these and determine which ones we want to follow.
I'll have to admit that even though it required a little extra work, I started enjoying google's :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13)*

**Comment by klappy** [comment]
*[index.js, line 4 at r2](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-KvMjHj_-EGtanQcEmcf:-KvMjHj_-EGtanQcEmcg:bupm35i) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/a821b4c64985ad657badff64ae0bf7b18ac228a3/index.js#L4)):*
> ```JavaScript
> var jsonToUsfm = require('./src/js/jsonToUsfm.js').jsonToUSFM;
> var filter = require('./src/js/filter');
> const fs = require('fs');
> ```

Doesn't look like we use this. We should only import in what we use in each file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13)*

**Comment by klappy** [comment]
Reviewed 24 of 24 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-:-KvMkS0AUpw1xegC7XCP:bnfp4nl)*

**Comment by klappy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.eslintrc.js, line 5 at r2](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-KvMiuX__6vWkA3GiPS2:-KvMkjWcY-hUR7aXmu0z:b32w0x) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/a821b4c64985ad657badff64ae0bf7b18ac228a3/.eslintrc.js#L5)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

What are these updated rules for? 
We should probably sync up on these and determine which ones we want to follow.
I'll have to admit that even though it required a little extra work, I started enjoying google's :)
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13)*

**Comment by klappy** [comment]
*[index.js, line 4 at r2](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-KvMjHj_-EGtanQcEmcf:-KvMklJXu0ODy0AP09uD:b32w0x) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/a821b4c64985ad657badff64ae0bf7b18ac228a3/index.js#L4)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Doesn't look like we use this. We should only import in what we use in each file.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13)*

**Comment by klappy** [comment]
@royalsix Do we need to update the Version number and make a new release for this functionality to be available?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/13#-:-KvMzWkeVZ3O5Crwpdo-:b-ixu3jc)*

**Comment by RoyalSix** [comment]
It's already been published. Check out the package version on https://www.npmjs.com/package/usfm-js

**Pull request merged**
