### PR TITLE
QA Fail - Requirement change #3756/put word tags on new line

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### changes:

on export, put word tags at start of line (unless after a quote)
also put milestones at start of line.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/usfm-js/35)

### CODE REVIEW

**Comment by klappy** [comment]
*[__tests__/resources/tit_1_12.usfm, line 12 at r1](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/35#-L6IV77KemJN91R4-1td:-L6IV77KemJN91R4-1te:b-vj7ox7) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/b8ad84f771501cc2d19b1c99f43c9180d5229c13/__tests__/resources/tit_1_12.usfm#L12)):*
> ```
> \w προφήτης|lemma="προφήτης" strong="G43960" x-morph="Gr,N,,,,,NMS,"\w*,
> “
> \w Κρῆτες|lemma="Κρής" strong="G29120" x-morph="Gr,N,,,,,NMP,"\w*
> ```

@jag3773: Just confirming that this is what we want here. Not sure if this is an exception as punctuation is commonly on the same line at the end of the word markers, should we do the same for beginning?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/35)*

**Comment by klappy** [comment]
Reviewed 13 of 14 files at r1.
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/35)*

**Comment by klappy** [comment]
Reviewed 1 of 14 files at r1.
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/35)*

**Comment by klappy** [comment]
Reviewed 1 of 14 files at r1.
Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/35)*

**Comment by richmahn** [comment]
:lgtm: Other than the issue @klappy raised, LGTM

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/35#-:-L6IdM0HKbl5C_lt2bWz:b-qhqw0z)*

**Comment by PhotoNomad0** [comment]
Review status: 8 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/resources/tit_1_12.usfm, line 12 at r1](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/35#-L6IV77KemJN91R4-1td:-L6NNt3xt5xizK_80xiL:b-896fix) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/b8ad84f771501cc2d19b1c99f43c9180d5229c13/__tests__/resources/tit_1_12.usfm#L12)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

@jag3773: Just confirming that this is what we want here. Not sure if this is an exception as punctuation is commonly on the same line at the end of the word markers, should we do the same for beginning?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/35)*

**Pull request merged**
