### PR TITLE
Feature #3273/Update greek resources to use UGNT

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Added milestone support for USFM import.  Also now uses new verse object format.

#### Test by reviewing updated grc resources in tc Resource: https://github.com/translationCoreApps/tC_Resources/pull/15

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/usfm-js/26)

### CODE REVIEW

**Comment by klappy** [comment]
@photonomad0: What's the difference between this one and beta.21? Is that in another PR?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/26#-:-L2fuPuBx42ecMk9zKmH:b1oor0b)*

**Comment by klappy** [comment]
Reviewed 3 of 14 files at r1, 35 of 35 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/26)*

**Comment by mannycolon** [comment]
After these changes is this library still functional for `USFM 2`? 
In other words, if i use this latest version of the usfm-js library in tC can i still import a usfm 2 project?

**Comment by klappy** [comment]
@mannycolon The application will not function and tests that rely on older USFM parsing will not work. We will have to handle other stories to get it to work again. For example, USFM import will have to be updated to import VerseObjects and convert those to the string format that we need. That is my next story I have tasked out is to update the importing of USFM to support verse objects.

**Comment by RoyalSix** [comment]
@klappy Is that stopping this from being merged?

**Pull request merged**
