### PR TITLE
Feature/3190&3209/preserve punctuation and Front Matter

### PR DESCRIPTION
**Pull request by PhotoNomad0**
## Includes fixes for issues: 
- https://github.com/unfoldingWord-dev/translationCore/issues/3209
- https://github.com/unfoldingWord-dev/translationCore/issues/3190

## Not yet supported:
- type attribute for all USFM markers

This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/usfm-js/22)

### CODE REVIEW

**Comment by klappy** [comment]
*[__tests__/resources/greek.json, line 20 at r2](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-8heMN-nuozoRYylZ1:-L-8heMN-nuozoRYylZ2:b-125ww3) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/e21b914258a73b5973ec891b1b3116b4ccf4cf0c/__tests__/resources/greek.json#L20)):*
> ```JSON
>         },
>         {
>           "word": "Παῦλος",
> ```

Would we want these to be the `text` attribute instead of `word`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by PhotoNomad0** [comment]
Review status: 0 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

*[__tests__/resources/greek.json, line 20 at r2](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-8heMN-nuozoRYylZ1:-L-94NjmgS_jsR_DkNTb:b-834n7i) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/e21b914258a73b5973ec891b1b3116b4ccf4cf0c/__tests__/resources/greek.json#L20)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Would we want these to be the `text` attribute instead of `word`?
</blockquote></details>

Oops

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 1 of 28 files at r3.
Review status: 1 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
*[__tests__/resources/greek.usfm, line 10 at r3](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-EA9NV_6jtph9inR6A:-L-EA9NWOmQBaCBwR5SG:b-t8v2cv) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/c5db7ac0b20eed54c41938960e307cec8386f67e/__tests__/resources/greek.usfm#L10)):*
> ```
> \w δοῦλος|lemma="δοῦλος" strong="G14010" x-morph="Gr,N,,,,,NMS,"\w*
> \w Χριστοῦ|lemma="Χριστός" strong="G55470" x-morph="Gr,N,,,,,GMS,"\w*
> \w κατὰ|lemma="κατά" strong="G25960" x-morph="Gr,P,,,,,A,,,"\w*
> ```

Could we add some punctuation at the end of this line?
There are verses that have punctuation like commas and periods, they are just inline to the `\w ...\w*,` and `\w ...\w*.`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
*[__tests__/resources/out_of_sequence_verses.usfm, line 8 at r3](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-ECaclTMJDuJol_frO:-L-ECacmFK9g3bvCTg0R:b-qj48g6) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/76563bb2bb620fcaf975bfaf4bc5d98fb78182cb/__tests__/resources/out_of_sequence_verses.usfm#L8)):*
> ```
> \toc3 Php
> \mt The Epistle of Paul the Apostle to the Philippians
> ```

Do we want to try to preserve these blank lines that were removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
*[__tests__/resources/psa_quotes.json, line 96 at r3](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-EDOrPKc3AMWHvL5tm:-L-EDOrPKc3AMWHvL5tn:b-owknxp) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/c5db7ac0b20eed54c41938960e307cec8386f67e/__tests__/resources/psa_quotes.json#L96)):*
> ```JSON
>         },
>         {
>           "tag": "q",
> ```

Should we add `"type": "quote"` for all quotes since we use these a lot? 
I'm wondering if whenever we have a use case for adding tests for them that we add the type attribute.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
*[__tests__/resources/tit_1_12.json, line 57 at r3](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-EDm01gQUdwSfrsrg2:-L-EDm01gQUdwSfrsrg3:bu5cqqk) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/c5db7ac0b20eed54c41938960e307cec8386f67e/__tests__/resources/tit_1_12.json#L57)):*
> ```JSON
>         {
>           "type": "text",
>           "text": ".”\n"
> ```

BTW: Awesome! Looks like we have a test for punctuation in Greek primary texts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
*[__tests__/resources/greek.usfm, line 10 at r3](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-EA9NV_6jtph9inR6A:-L-EDzh9K0eZm7tQzgte:bc0r64g) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/c5db7ac0b20eed54c41938960e307cec8386f67e/__tests__/resources/greek.usfm#L10)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Could we add some punctuation at the end of this line?
There are verses that have punctuation like commas and periods, they are just inline to the `\w ...\w*,` and `\w ...\w*.`
</blockquote></details>

OK: Found tests with punctuation in another test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 6 of 32 files at r2, 19 of 28 files at r3.
Review status: 26 of 38 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
This is looking really good and consistent.
Most of my questions were about new test cases that were resolved when looking at other tests.

I'm thinking of even tC projects using the JSON representation of each verse and we can convert the individual verse/span to USFM when displaying it in the Editor boxes. That way they can edit the raw USFM and we can then validate it and convert it back to JSON when saving.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-:-L-EEwS5H3xv6ltBGXMh:b-uqjuqd)*

**Comment by PhotoNomad0** [comment]
Review status: 12 of 37 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[__tests__/resources/greek.usfm, line 10 at r3](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-EA9NV_6jtph9inR6A:-L-HaHhWk6BfgDvBjL6D:b-896fix) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/c5db7ac0b20eed54c41938960e307cec8386f67e/__tests__/resources/greek.usfm#L10)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

OK: Found tests with punctuation in another test.
</blockquote></details>

Done.

---

*[__tests__/resources/out_of_sequence_verses.usfm, line 8 at r3](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-ECaclTMJDuJol_frO:-L-H_m9vpxBWhL68UQh4:b-z9sh8h) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/76563bb2bb620fcaf975bfaf4bc5d98fb78182cb/__tests__/resources/out_of_sequence_verses.usfm#L8)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Do we want to try to preserve these blank lines that were removed?
</blockquote></details>

Sounds good, rewriting  header to be an array of USFM objects rather than key/value so we can support lines as text.

---

*[__tests__/resources/psa_quotes.json, line 96 at r3](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-EDOrPKc3AMWHvL5tm:-L-HaJhubiwAn48KDtbN:b-896fix) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/c5db7ac0b20eed54c41938960e307cec8386f67e/__tests__/resources/psa_quotes.json#L96)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Should we add `"type": "quote"` for all quotes since we use these a lot? 
I'm wondering if whenever we have a use case for adding tests for them that we add the type attribute.
</blockquote></details>

Done.

---

*[__tests__/resources/tit_1_12.json, line 57 at r3](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-EDm01gQUdwSfrsrg2:-L-HaLQqrP57bpT8VrbU:b-896fix) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/c5db7ac0b20eed54c41938960e307cec8386f67e/__tests__/resources/tit_1_12.json#L57)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

BTW: Awesome! Looks like we have a test for punctuation in Greek primary texts.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by mannycolon** [comment]
Reviewed 1 of 24 files at r1, 3 of 32 files at r2, 2 of 28 files at r3, 21 of 22 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 1 of 24 files at r1, 2 of 32 files at r2, 7 of 28 files at r3, 1 of 22 files at r4, 2 of 11 files at r5.
Review status: 30 of 37 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 1 of 11 files at r5.
Review status: 30 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
:lgtm:

---

Reviewed 16 of 22 files at r4, 7 of 11 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-:-L-IudufOD_y7PysGNfa:bnfp4nl)*

**Comment by klappy** [comment]
Because of this breaking change, I would typically suggest bumping the major version but since we're still in beta, I think we can increment the beta number.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-:-L-IulEmloFqY92tc8X4:biwgyoa)*

**Comment by klappy** [comment]
*[package.json, line 3 at r6](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-JJQWGXt7h14AEm_Mw:-L-JJQWGXt7h14AEm_Mx:b-4wtiba) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/64284b571b3f5b6cf0abf0e57b22afd1ee7fbf5b/package.json#L3)):*
> ```JSON
> {
>   "name": "usfm-js",
>   "version": "2.0.0-beta.1",
> ```

What do you think of just doing 1.0.0-beta.18? Since we haven't released it, we can change the spec.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 6 of 7 files at r6.
Review status: 39 of 40 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by PhotoNomad0** [comment]
Review status: 30 of 42 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 3 at r6](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-L-JJQWGXt7h14AEm_Mw:-L-M_s91s-JIxcYKpiyw:b-896fix) ([raw file](https://github.com/translationcoreapps/usfm-js/blob/64284b571b3f5b6cf0abf0e57b22afd1ee7fbf5b/package.json#L3)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

What do you think of just doing 1.0.0-beta.18? Since we haven't released it, we can change the spec.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 14 files at r7.
Review status: 31 of 42 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by PhotoNomad0** [comment]
@klappy - Have it working converting the whole en ULB round trip USFM->JSON->USFM with the exception of not preserving a trailing space on chapter in Joshua (`\c 10 `).  I don't think it's worth the effort to preserve this since it really shouldn't be there in the first place.

**Comment by PhotoNomad0** [comment]
@klappy - Have added removal of leading zeroes in chapters and verse numbers since they will be in tstudio exports.

Is there any error (or sloppy syntax) test cases that you think we should add?  
Here are a few I can think of:
```
- "\v5"
- "\v 5-"
- "\v 5 -6"
- "\v 5 - 6"
- "\v 5-6Mashed"
- "\v 5Mashed"
- "\v  5"
- "\v No number"
- "\v"
```

**Comment by klappy** [comment]
@photonomad0: 

The following should be recoverable and should parse properly:
- What do you think of making mashed parse even by making the space optional in the regex?
- The extra whitespace between \v and the numbers should be easy via regex `\s+` for spaces.
- The whitespace in the verse span could be solved with optional whitespace `\d+\s*-\s*\d+`.

The following should return an error:
- The missing verse number after \v whether text is there or not.

I'm not sure about the following:
- The `\v5` could be solved by making the `\\v\s*\d+` but that may complicate it as it has to be a special case and may conflict with code that parses markers that actually use digits. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-:-L-TNqlElxuYobLsDCyi:bgx0nwf)*

**Comment by klappy** [comment]
Reviewed 1 of 14 files at r7.
Review status: 31 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 1 of 14 files at r7.
Review status: 32 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 1 of 5 files at r8.
Review status: 33 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 1 of 5 files at r8.
Review status: 34 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 1 of 5 files at r8.
Review status: 35 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 1 of 14 files at r7.
Review status: 35 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 1 of 14 files at r7.
Review status: 36 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 6 of 14 files at r7.
Review status: 40 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 1 of 14 files at r7.
Review status: 41 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 1 of 5 files at r8.
Review status: 42 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
Reviewed 2 of 5 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22)*

**Comment by klappy** [comment]
With all of that said, the way it stands, with all of those use cases returning an error is good. We can just consider the above comments for the future.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-:-L-XKK2N5quwm7hsNvAT:b2tbnx6)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-:-L-XKUMGrIOsP4X7CNWm:bnfp4nl)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/usfm-js/22#-:-L-XNB33TnC_Cnn8OHJd:bnfp4nl)*

**Pull request merged**
